version: "1.0.0"
services:
  explore-engine-server:
    image: vijaykumar151096/explore-engine-server:latest
    ports:
      - 8080:8080
  explore-engine-view:
    image: vijaykumar151096/explore-engine-view:latest
    ports:
      - 3000:3000
