version: "3.8"
services:
  explore-engine-server:
    image: vijaykumar151096/explore-engine-server:elastic
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch

  explore-engine-view:
    image: vijaykumar151096/explore-engine-view:elastic
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=1234
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          memory: 4g

volumes:
  esdata:
    driver: local
